Вкладка: Обновлены ссылки на справку для вкладки "ОВиВК"
Bim4Everyone/HVACExtension pull request #16
Opened 2024-07-09 08:56 UTC by Redomine

Добавлены метаданные, обновлены ссылки и имена иконок, удалены мусорные устаревшие и скрытые плагины.

2024-07-09 11:14 UTC, sssenya requested changes

2024-07-09 13:26 UTC, sssenya submitted a review, later dismissed

2024-07-09 15:20 UTC, dosymep requested changes

2024-07-09 15:20 UTC, dosymep commented on ОВиВК.tab/BIM.panel/BIM.pulldown/Параметры для электриков.pushbutton/bundle.yaml
> +  en_us: Parameters fo EOM
for :)

2024-07-11 06:41 UTC, dosymep approved these changes

2024-07-11 06:48 UTC, sssenya approved these changes

2024-07-11 06:48 UTC, merged